version: '3'

services:
  # PostgreSQL Database for Judge0
  db:
    image: postgres:13.0
    env_file: ./judge0-env/judge0.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  # Redis for Judge0 worker queue
  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./judge0-env/judge0.env
    volumes:
      - redis-data:/data
    restart: always

  # Judge0 API service
  api:
    image: judge0/judge0:1.13.0
    env_file: ./judge0-env/judge0.env
    ports:
      - "2358:2358"
    volumes:
      - ./judge0-env/judge0-config.yml:/judge0.conf:ro
    privileged: true
    depends_on:
      - db
      - redis
    restart: always

  # Judge0 Workers
  worker:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    env_file: ./judge0-env/judge0.env
    volumes:
      - ./judge0-env/judge0-config.yml:/judge0.conf:ro
    privileged: true
    depends_on:
      - db
      - redis
      - api
    restart: always
    
  # Simple UI for testing - optional, you can access via your own UI
  ui:
    image: judge0/judge0-ce-ui:1.1.0
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:2358
    depends_on:
      - api
    restart: always

volumes:
  postgres-data:
  redis-data: