[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "npm run build"

# Environment variables for production
[build.environment]
  VITE_API_BASE_URL = "https://acemyinterview-production.up.railway.app"
  VITE_API_URL = "https://acemyinterview-production.up.railway.app/api"
  VITE_APP_NAME = "AceMyInterview"
  VITE_APP_VERSION = "1.0.0"

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: API calls go directly to Railway backend
# https://acemyinterview-production.up.railway.app/api

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
