debug: false
production: true
max_attributes: 20
authentication:
  header: "X-Auth-Token"
submissions:
  default_cpu_time_limit: 2
  default_wall_time_limit: 5
  default_memory_limit: 128000
  default_stack_limit: 64000
  default_max_processes_and_or_threads: 60
  default_max_file_size: 30
trusted_users:
  enabled: false
enable_per_runtime:
  python: true
  javascript: true
  cpp: true
  c: true
  java: true
  ruby: true
  rust: true
  go: true
  php: true
  kotlin: true
  swift: true
  csharp: true
  fsharp: true
  haskell: true
  perl: true
  pascal: true
  r: true
  scala: true
  julia: true
  fortran: true
  prolog: true
  octave: true
  nasm: true
  clojure: true
  elixir: true
  mcs: true
  mono: true
  bash: true
